import { Inter } from "next/font/google";
import "./globals.css"; 
import Header from "./components/Layout/Header";
import Footer from "./components/Layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Js File Upload",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
		<head>
		</head>
		<body className={inter.className}>
			<Header />
			<div className="container mx-auto px-4">
			{children}
			</div>
			<Footer />
		</body>
		</html>
	);
}
